FROM python:3.8-slim

RUN apt-get update

WORKDIR /app

COPY env/requirements.txt .
RUN pip install -r requirements.txt

COPY src/ .

#CMD ["python", "main.py"]
ENTRYPOINT ["uvicorn", "--host", "0.0.0.0", "main:app"]
